services:
  libsql:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
      - "5001:5001"
    volumes:
      - ./.data/libsql:/var/lib/sqld
    environment:
      - SQLD_HTTP_LISTEN_ADDR=0.0.0.0:8080
      - SQLD_HTTP_AUTH=basic:Y29uc29sZTpjb25zb2xlMTIzNCE=
  minio:
    image: muscaa/minio:latest
    platform: linux/amd64
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./.data/minio:/data
    environment:
      - MINIO_ROOT_USER=console
      - MINIO_ROOT_PASSWORD=console1234!
